### PR TITLE
Add support for SEVIRI Native

### PR DESCRIPTION
**Pull request by sfinkens**
Add support for SEVIRI L1.5 data in Native format as provided in the European Weather Cloud. 

Depends on 

- https://github.com/pytroll/satpy/pull/1457
-  https://github.com/pytroll/satpy/pull/1468
-  https://github.com/pytroll/satpy/pull/1609
 - https://github.com/pytroll/satpy/pull/1612

Also adds two new flags for `seviri2pps`:
-  `--use-nominal-time-in-filename` to use nominal timestamp for the output filename
- `--no-sun-earth-distance-correction` to disable sun-earth-distance-correction (needed by CPP)

### CODE REVIEW

**Review by ninahakansson — APPROVED** [review]
Looks good!

**Comment by sfinkens** [comment]
Thanks for reviewing the changes @ninahakansson ! I think we can leave this PR open until the satpy PRs are merged, just in case something changes there.

**Comment by sfinkens** [comment]
Oops, sorry for the noise

**Comment by mraspaud** [comment]
All these PR's have been merged and released :)

**Pull request merged**
