### PR TITLE
Use satpy to rotate SEVIRI images

### LINKED ISSUE #40: Use satpy to rotate SEVIRI image
Satpy now offers the possibility to rotate GEO images as follows:

```python
scn.load(['VIS008'], upper_right_corner='NE')
```

This could replace `level1c4pps.seviri2pps_lib.rotate_band()`.

### PR DESCRIPTION
**Pull request by sfinkens**
Closes #40

### CODE REVIEW

**Comment by sfinkens** [comment]
Due to merge conflicts I would wait for #50 to be merged before continuing here.

**Comment by ninahakansson** [comment]
I just merged #50, is this ready to be merged as well?

**Comment by sfinkens** [comment]
Yes! I'll resolve the merge conflicts later today.

**Review by ninahakansson — APPROVED** [review]
LGTM!

**Pull request merged**
