### PR TITLE
Update MSG-4 visible calibration coefficients

### PR DESCRIPTION
**Pull request by sfinkens**
Update MSG-4 visible calibration coefficients to latest version from May 2023: https://msgcpp.knmi.nl/solar-channel-calibration.html

**Edit 1**

For some reason creating the conda environment on macos failed (see https://github.com/foua-pps/level1c4pps/actions/runs/5785938956):
```
ImportError: dlopen(...libmambapy/bindings.cpython-311-darwin.so, 0x0002): Library not loaded:
...
Error: The process '/Users/runner/miniconda3/condabin/mamba' failed with exit code 1
```

Switching to mambaforge seems to solve the problem.

**Edit 2**

Now creating the conda env with Python-3.8 takes forever... 

I noticed some warnings about deprecated node 12 (https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/) so I updated `actions/checkout` and `codecov/codecov-action` to version 3. But that doesn't speed things up...

 - [X] Tests added 
 - [x] Tests passed: Passes ``pytest level1c4pps`` 
 - [X] Passes ``flake8``

### CODE REVIEW

**Comment by ninahakansson** [comment]
Can we just remove support for python 3.8? Or do you still need to run level1c4pps for python-3.8?

**Comment by sfinkens** [comment]
> Can we just remove support for python 3.8? Or do you still need to run level1c4pps for python-3.8?

Forwarding this to @yeigenbrodt :slightly_smiling_face:

**Comment by yeigenbrodt** [comment]
> Can we just remove support for python 3.8? Or do you still need to run level1c4pps for python-3.8?

I see no reason to support 3.8.

**Comment by sfinkens** [comment]
I simplified the satpy version requirement a little (> 0.41), which speeds up the build a bit:

| OS | Python | Build time old [min] | Build time new [min] |
| --- | --- | --- | --- |
| ubuntu |3.9 | inf | 22 |
| ubuntu |3.10 | 116 | 11 |
| ubuntu |3.11 | 13 | 3 |
| macos |3.9 | inf | 46 |
| macos |3.10 | 37 | 22 |
| macos |3.11 | 14 | 8 |

So at least from the Python-3.11 jobs you get a quick feedback. But 46 minutes for Python-3.9 is way too long... Any idea how to speed this up?

**Comment by mraspaud** [comment]
I see this is already using mamba, which I was going to suggest. I'm very surprised it takes such a long time with mamba though...
As for ways to improve this, maybe the requirements file should be trimmed down? Satpy has hard requirements on pyresample, dask and xarray at least, so these can go.

**Comment by sfinkens** [comment]
> As for ways to improve this, maybe the requirements file should be trimmed down?

That helped a lot! Now at 6 minutes max :slightly_smiling_face: 

@ninahakansson From my point of view this is ready to merge now.

**Pull request merged**
