### PR TITLE
Mersi2

### PR DESCRIPTION
**Pull request by adybbroe**
Add support for MERSI-2

### CODE REVIEW

**Review by ninahakansson — COMMENTED** [review]
Nice to be prepared for xarray!

I thought this: 

 daz[daz > 180] = 360 - daz[daz > 180]

was faster compared to np.where, as np.where will create a new copy of the matrix.

**Comment by adybbroe** [comment]
@ninahakansson Oh yes, you are probably right. I was trying to convert it for xarray where you can't do this kind of indexing. Thought I could use np.where and that this would work for both. Turned out I couldn't, and left it...
I will fix it...

**Comment by adybbroe** [comment]
@ninahakansson Is it okay, can I merge?

**Review by ninahakansson — COMMENTED** [review]
When it comes to the long_names and standard names of angles:

scn_['satzenith'].attrs['long_name'] = 'sensor zenith angle'
scn_['satzenith'].attrs['stadard_name'] = 'sensor_zenith_angle'

they are now different from pps:

setattr(var, "standard_name", "platform_zenith_angle")
setattr(var, "long_name", "satellite zenith angle")

It would be better to update to the better names in PPS and level1c4pps at the same time. But as mersi22pps is a new feature maybe it is ok. Can PPS already handle the updated names?

**Comment by adybbroe** [comment]
Ok, unsure about what is most CF here, but I can try to allign with how PPS wants it (which is probably as close as possible to CF) @shornqui ?

**Pull request merged**
