### PR TITLE
Final Tweaks for CLAAS-3

### LINKED ISSUE #18: Update SEVIRI calibration
Update SEVIRI calibration to use JF's new coefficients: http://msgcpp.knmi.nl/mediawiki/index.php/MSG-SEVIRI_solar_channel_calibration

### PR DESCRIPTION
**Pull request by sfinkens**
- Remove resampling. The offset is half a pixel, NN resampling can't change that. So we decided to provide the level 2 data on the native grid. Even if that means having a grid change in the timeseries and 2 sets of auxiliary data.
- Update MSG-4 calibration coefficients
- Remove option to compute buggy angles on purpose (hope that is ok?)
- Fixed invalid angles outside the disk by setting invalid lon/lat to NaN. Then the corresponding angles are NaN, too.
- Compute solar angles using scanline acquisition times (runtime penalty ~ 3 seconds).
- Update chunksizes to improve performance. I experimented a bit and with the current setting I could reduce the runtime by 50% to about 30 seconds on my machine.
- Use nominal timestamps in the output filename. That makes it easier to match output with input.
- Move some attributes repeated for each variable to global attributes
- Lots of refactoring to facilitate unit tests

I will also send an example nc file to Jan Fokke and ask him to double-check the angles.

TODO
  - [x] Remove encoding hacks ("True") if https://github.com/pytroll/satpy/pull/953 is resolved
  - [ ] Wait for Jan Fokke's approval of the sample file
  - [X] Closes #18

### CODE REVIEW

**Comment by ninahakansson** [comment]
Thanks for the contribution, it is a big improvement of the code! Very nice that you even thought about processing time, also on my computer the processing time is now less than 50%.

Absolutely OK to remove the option to create buggy angles, it was only there to give possibility to reproduce exactly earlier versions of test data. But I can not see it should be needed any longer.

I tested the code and I think it can be merged.  

I have just one comment that you can add your name to the authors in the header of seviri2pps_lib.py and seviri2pps.py.

**Review by ninahakansson — APPROVED** [review]
Thanks for the contribution, it is a big improvement of the code! Very nice that you even thought about processing time, also on my computer the processing time is now less than 50%.

Absolutely OK to remove the option to create buggy angles, it was only there to give possibility to reproduce exactly earlier versions of test data. But I can not see it should be needed any longer.

I tested the code and I think it can be merged.

I have just one comment that you can add your name to the authors in the header of seviri2pps_lib.py and seviri2pps.py.

**Review by adybbroe — APPROVED** [review]
LGTM

**Comment by adybbroe** [comment]
And thanks for the nice work @sfinkens !

**Comment by sfinkens** [comment]
@adybbroe You're welcome, my pleasure! Sorry that the PR has become so big :sweat_smile:

**Pull request merged**
