### PR TITLE
Make a python package out of the scripts

### PR DESCRIPTION
**Pull request by adybbroe**
Signed-off-by: Adam Dybbroe <Adam.Dybbroe@smhi.se>

### CODE REVIEW

**Review by ninahakansson — COMMENTED** [review]
Is it better that the scripts are in bin? Should they not be in level1c4pps/level1c4pps/bin, to keep the main directory more empty? 

I might miss the version.py file.

The file severi2pps.py seem to be moved and changed.

**Comment by adybbroe** [comment]
@ninahakansson  I think it is standard to collect all executables/scripts together as long as the main package is not really big with many sub-packages. I suppose you could as you suggest also. The important thing is that the scripts end up in the (same) bin-directory upon installation. Maybe @mraspaud want to comment on this?

Concerning the version.py file the versioning is now supposed to be handled by `setuptools_scm` package. I think it is handy. It will handle the versioning also between tags.

Yes, I have moved the main functionality in under package, so other applications can import from it

**Comment by adybbroe** [comment]
I will make few more clean ups concerning gac then, and then we can merge hopefully

**Comment by adybbroe** [comment]
@ninahakansson and @mraspaud There is a `make_azidiff_angle` function in both the conversion scripts, but they are not equal. I propose a third variant (as martin pointed out in the third line it shouldn't be necessary to check the angle range:
```
def make_azidiff_angle(sata, suna, fill):
    """ Calculate azimuth difference angle """
    daz = sata - suna
    daz[daz < 0] = -1 * daz[daz < 0]
    daz = daz % 360
    daz[daz > 180] = 360 - daz[daz > 180]
    return daz
```

**Comment by ninahakansson** [comment]
@adybbroe Ok, thanks!

**Pull request merged**
